## makeCacheMatrix and cacheSolve cache a matrix and calculate its inverse,
## caching it as well for ease of future use.

##Testing pattern used:
##  > a <- matrix(c(2, 4, 3, 1), nrow=2, ncol=2, byrow = TRUE)
##  > b <- makeCacheMatrix(a)
##  > cacheSolve(b)
##  > cacheSolve(b) ##repeated to demonstrate cache retrieval.

##Change matrix "a" in order to reset caching.
##  > a <- matrix(c(3, 4, 3, 1), nrow=2, ncol=2, byrow = TRUE)
##Repeat from "b <- makeCacheMatrix(a)"

## makeCacheMatrix caches a matrix, and its inverse if this is supplied.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <<- function(y){
    x <<- y
    inv <<- NULL
  }
  get <- function() {
    x
  }
  setInv <- function(a) {
    inv <<- a
  }
  getInv <- function() {
    inv
  }
  list(set = set, get = get, setInv = setInv, getInv = getInv)
}


## cacheSolve takes a pseudo-"matrix" as generated by makeCacheMatrix,
## and inverts it, returning the value and caching it to the argument
## for convenience in future use. For this reason, the argument must be
## an extant object: you cannot call cacheSolve(makeCacheMatrix(foo))
cacheSolve <- function(x, ...) {
  inv <- x$getInv()
  if(!is.null(inv)) {
    message("getting cached data. . .")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data)
  x$setInv(inv)
  inv
}